### ISSUE TITLE
Critical error , can't add post, blog etc.

### ISSUE THREAD

**Issue by mtdas99** [wordpress-premium/wordpress-seo-premium#2]
After activating SEO Premium error showing: There has been a critical error on this website. Please check your site admin email inbox for instructions.
**Issues:**

WordPress version 6.4.3 Active theme: Rehub child theme (version 9.4) Current plugin: Yoast SEO Premium (version 17.9) PHP version 8.3.3 Error Details ============= An error of type E_ERROR was caused in line 105 of the file /home/tlkfxuu/public_html/wp-content/plugins/wordpress-seo-premium-master/classes/premium-metabox.php. Error message: Uncaught Error: Class "WPSEO_Admin_Asset_Yoast_Components_L10n" not found in /home/tlkfxuu/public_html/wp-content/plugins/wordpress-seo-premium-master/classes/premium-metabox.php:105 Stack trace: #0 /home/tlkfxuu/public_html/wp-includes/class-wp-hook.php(324): WPSEO_Premium_Metabox->enqueue_assets() #1 /home/tlkfxuu/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #2 /home/tlkfxuu/public_html/wp-includes/plugin.php(517): WP_Hook->do_action() #3 /home/tlkfxuu/public_html/wp-admin/admin-header.php(118): do_action() #4 /home/tlkfxuu/public_html/wp-admin/edit-form-advanced.php(425): require_once('/home/tlkfxuu/p...') #5 /home/tlkfxuu/public_html/wp-admin/post-new.php(75): require('/home/tlkfxuu/p...') #6 {main} thrown

**Comment by thaikolja** [comment]
I've updated the plugin to the latest version, v22.2. Please download it and try again.
